import { lingui, linguiTransformerBabelPreset } from "@lingui/vite-plugin";
import babel from "@rolldown/plugin-babel";
import { defineConfig } from "vite";

import { shikiLangsPlugin } from "./vite-plugins/vitePluginCopyShikiLangs.ts";
import { googleFontsLocal } from "./vite-plugins/vitePluginGoogleFontsLocal.ts";
import { devRerenderHighlighter } from "./vite-plugins/vitePluginRerenderHighlighter.ts";

export default defineConfig({
  resolve: {
    alias: {
      "@trans": "/src/macro.ts",
      "@trans-runtime": "/src/Trans.ts",
      "@nerimity/jsx": "/src/jsx-runtime",
    },
  },
  plugins: [
    shikiLangsPlugin(),
    devRerenderHighlighter(),
    googleFontsLocal({
      icons: [
        "skull",
        "wallpaper",
        "cognition",
        "password",
        "sell",
        "panorama",
        "image",
        "undo",
        "person",
        "account_circle",
        "add_reaction",
        "add",
        "visibility",
        "search",
        "error",
        "verified",
        "heart_broken",
        "group_add",
        "person_add_disabled",
        "do_not_disturb_on",
        "add_circle",
        "person_add",
        "volunteer_activism",
        "crown",
        "robot_2",
        "crowdsource",
        "shield",
        "favorite",
        "verified_user",
        "cruelty_free",
        "sound_detection_dog_barking",
        "pets",
        "group",
        "save",
        "calendar_month",
        "social_leaderboard",
        "keyboard_return",
        "bar_chart",
        "settings",
        "notifications_off",
        "volume_off",
        "history",
        "gif",
        "face",
        "gpp_maybe",
        "brush",
        "deceased",
        "open_in_new",
        "warning",
        "terminal",
        "music_note",
        "movie",
        "gamepad",
        "folder_open",
        "attach_file",
        "download",
        "schedule",
        "draft",
        "upload_file",
        "logout",
        "block",
        "call",
        "trending_up",
        "keep",
        "article_person",
        "book",
        "mail",
        "keyboard_arrow_down",
        "check",
        "chevron_forward",
        "reply",
        "wrap_text",
        "content_copy",
        "alternate_email",
        "cached",
        "close",
        "delete",
        "diversity_1",
        "edit",
        "home",
        "inbox",
        "info",
        "login",
        "more_horiz",
        "pending",
        "segment",
        "send",
        "side_navigation",
        "tag",
      ],
    }),
    lingui(),
    babel({
      presets: [linguiTransformerBabelPreset()],
    }),
  ],

  oxc: {
    jsx: {
      pragma: "h",
      pragmaFrag: "Fragment",
    },
  },
  build: {
    sourcemap: true,
  },
  server: {
    port: 3000,
    host: true,
    allowedHosts: ["local.nerimity.com"],

    watch: {
      ignored: ["**/vitePluginRerenderhighlighter.ts"],
    },
  },
  preview: {
    port: 3000,
  },
});
